// src/routes/tutorRoutes.js
import express from "express";
import multer from "multer";
import path from "path";
import fs from "fs";
import {
  createRegistrationSession,
  confirmRegistrationPayment,
  getTutors,
  getTutorById,
  updateProfile,
  loginTutor,
  deleteTutor,
} from "../controllers/tutorController.js";
import authMiddleware from "../middlewares/auth.js";

const tutorRouter = express.Router();

// simple multer config (stores files in ./uploads with autogenerated filenames)
const storage = multer.diskStorage({
  destination: (req, file, cb) => {
    cb(null, path.join(process.cwd(), "uploads")); // ➜ ./uploads
  },
  filename: (req, file, cb) => {
    const unique = Date.now() + "-" + Math.round(Math.random() * 1e9);
    const ext = path.extname(file.originalname);
    cb(null, `tutor-${unique}${ext}`);
  },
});
const upload = multer({ storage });

tutorRouter.post("/create-registration-session", upload.single("profilePicture"), createRegistrationSession);
tutorRouter.get("/confirm-payment", confirmRegistrationPayment);
tutorRouter.post("/login", loginTutor);
tutorRouter.get("/", getTutors);
tutorRouter.get("/:id", getTutorById);
tutorRouter.put("/:id", authMiddleware, upload.single("profilePicture"), updateProfile);
tutorRouter.delete("/:id", deleteTutor);

export default tutorRouter;
